urls = (
    '/', 'application.controllers.main.index.Index',
    '/404', 'application.controllers.main.notfound.NotFound',
    '/500', 'application.controllers.main.internalerror.InternalError',
    "/login", "application.controllers.main.login.LoginPage",
    "/loginselection", "application.controllers.main.loginselection.LoginSelection",
    "/logout", "application.controllers.main.logout.Logout",
    "/auth/(google)", "application.controllers.main.login.AuthPage",
    "/auth/(google)/callback", "application.controllers.main.login.AuthCallbackPage",
    '/users', 'application.controllers.users.index.Index',
    '/users/printer', 'application.controllers.users.printer.Printer',
    '/users/view/(.+)', 'application.controllers.users.view.View',
    '/users/edit/(.+)', 'application.controllers.users.edit.Edit',
    '/users/delete/(.+)', 'application.controllers.users.delete.Delete',
    '/users/insert', 'application.controllers.users.insert.Insert',
    '/users/csv_import', 'application.controllers.users.csv_import.CsvImport',
    '/logs', 'application.controllers.logs.index.Index',
    '/logs/printer', 'application.controllers.logs.printer.Printer',
    '/logs/view/(.+)', 'application.controllers.logs.view.View',
   )